### ISSUE TITLE
Resources utilization graphics immediately available under tab

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#101]
I would be great to have the resources utilization graphics readily available here, for convenience:
![image](https://github.com/flatironinstitute/dendro/assets/24541631/e9499477-676d-4b12-a559-5b00152c1d35)

I think enlarging for more precise inspections is still quite necessary though

**Comment by luiztauffer** [comment]
oh, and it would be great to be able to export the full plotly figure as well!

**Comment by magland** [comment]
@luiztauffer There is a menu button on the plotly plot that let's you download as PNG. Hover to see the menu appear.

**Comment by magland** [comment]
Oh I see... export the FULL plotly figure. That's not easy.

**Comment by magland** [comment]
The resource utilization plot is now inline, with an option to view enlarged version. @luiztauffer 

![image](https://github.com/flatironinstitute/dendro/assets/3679296/348ab404-f202-431a-a0d6-8a642c20040d)

**Comment by luiztauffer** [comment]
@magland its looking great, thanks!
I guess to export the full image we would need to produce a single Plotly figure with subplots

**Comment by magland** [comment]
> @magland its looking great, thanks! I guess to export the full image we would need to produce a single Plotly figure with subplots

Yeah I think you're right. I don't think I'm going to prioritize that right now.
