### ISSUE TITLE
Starting compute resource always creates new revision for job definitions

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#109]
Every time we restart a compute resource controller, we're creating a new revision version for each job definition in AWS Batch
Maybe we should avoid doing this, and instead use always the latest version.

![image](https://github.com/flatironinstitute/dendro/assets/24541631/75a1e87d-2e91-46be-94d4-7de814f0163d)

**Comment by magland** [comment]
I think we should check whether the existing definition is consistent with the new one, and if so, do nothing. It's possible that the docker image or something else might change.
