### ISSUE TITLE
DANDI Import screen blank on New Project

### ISSUE THREAD

**Issue by CodyCBakerPhD** [scratchrealm/protocaas#129]
Trying to test opening of multiple files with neurosift through dendro

Workflow:

- make a new project
- click 'Files' -> '+ DANDI Import'
- blank screen

![image](https://github.com/flatironinstitute/dendro/assets/51133164/6d22c553-1d34-41c9-a365-8010191653bd)

Screenshots attached to the documentation, such as https://flatironinstitute.github.io/dendro-docs/docs/intro#import-files-from-dandi-into-a-dendro-project, could help clarify expected behavior for first time users; I had to try a bunch of other approaches to try to get it to work as expected

I also tried specifying both API keys and that did not make any files viewable

After trying a bunch of other things, what worked in the end was going to 'manage projects' from the main dendro landing page, then the 'import from dandi' button at the top, selecting a dataset, then selecting 'Create a new dendro project for this dandiset'

![image](https://github.com/flatironinstitute/dendro/assets/51133164/f559e837-6026-4034-9169-a815f498265e)

(there's also a bunch of projects there that I don't remember making?)

**Comment by magland** [comment]
Thanks for that report. It's now possible to click to associate a dandiset with a project from the DANDI Import tab. That should address part of the issue. (should be deployed in a few minutes)
