### ISSUE TITLE
Keep Refresh button always on screen

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#136]
When the `Console output` is too long and we need to scroll down to see the most recent logs (almost every time), we need to scroll back up to be able to click on the `Refresh` button.
I think we should have either:
- a scroll bar specific to the `Console output` text area
- the `Refresh` and `Export job` buttons outside the current scroll bar, so they're always fixed in that part of the screen.

![Peek2024-03-2013-35-ezgif com-crop](https://github.com/flatironinstitute/dendro/assets/24541631/a7ee0f85-5c0a-48cc-b4c0-45a658cab871)

**Comment by magland** [comment]
@luiztauffer I have added a scrollbar to the console output. Try it out and see if it is suitable. It's a bit tricky figuring out the optimal heights for the various widgets.

**Comment by luiztauffer** [comment]
already much better, thanks!

**Comment by luiztauffer** [comment]
actually, the problem of "loosing" tge refresh button persists when we open other tabs like `Resource utilization`.
I suggest we leave the first row buttons outside if the div with the yscroll

**Comment by magland** [comment]
@luiztauffer There is now a refresh button specific for the console output. Does that do the trick?

**Comment by luiztauffer** [comment]
yes that works, thanks!
