### ISSUE TITLE
Job parameters list showing under `Files`

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#137]
We're showing a list of job parameters under the `Files` session, I believe this is a bug.

![image](https://github.com/flatironinstitute/dendro/assets/24541631/cc60c901-8fdc-4847-8542-27404d643911)

@magland

**Comment by magland** [comment]
@luiztauffer This should be fixed now.

**Comment by luiztauffer** [comment]
@magland it is fixed, thanks!
