### ISSUE TITLE
Choose between dandi standard vs staging archive

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#138]
It would be great to have an option to choose between standard archive or staging archive when importing a dandiset to a dendro project, possibly in this dialog?

![image](https://github.com/flatironinstitute/dendro/assets/24541631/b07233a2-2282-4332-8c44-c0506acdb635)

@magland what do you think?

**Comment by magland** [comment]
There is now a checkbox that allows you to switch on/off staging

![image](https://github.com/flatironinstitute/dendro/assets/3679296/4d299370-175f-4e82-9013-23abfcb1fcc5)

Note: it is not possible to mix staging / non-staging for a given project. In other words you can't associate a regular dandiset and a staging dataset to the same project. So if a dandiset has already been associated, then the checkbox will be disabled.

@luiztauffer

**Comment by luiztauffer** [comment]
@magland insteresting, that's good to know, thanks!
