### ISSUE TITLE
Jobs not running in new Compute Resource

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#21]
@magland 
Apparently all these steps worked alright:
- register a Compute Resource
- install an App through the GUI (url to the spec file)
- start the compute resource
- create a Project from a specific dandiset
- add the Compute Resource to the Project
- import files to the Project
- select a file with `/acquisition/ElectricalSeries` and a sorter Processor from the installed App
- submit job

But the Job seems to be stuck and going nowhere: 
- No error message
- no docker activity when inspecting with `docker ps`
- no network activity in my CR

The following logs get printed in my CR terminal:
```
Loading app https://github.com/scratchrealm/pc-spike-sorting/blob/main/kilosort2_5/spec.json | 
  2 processors
Loaded apps: kilosort2_5
Reporting the compute resource spec
Getting pubsub info
Starting compute resource
Starting job 19ba7494 ks2_5_quicktest
Warning: unable to import client keys from kachery_cloud
Running: docker run -it v /home/luiz/Desktop/protocaas/compute_resource/jobs/19ba7494/tmp:/tmp --workdir /tmp/working -e PYTHONUNBUFFERED=1 -e JOB_ID=19ba7494 -e JOB_PRIVATE_KEY=ed303aac0f4644d2a8c88978b4de6778 -e APP_EXECUTABLE=/app/main.py -e PROTOCAAS_URL=https://protocaas.vercel.app magland/pc-kilosort2_5 /app/main.py
```

The GUI shows this:
![image](https://github.com/scratchrealm/protocaas/assets/24541631/7b873cd3-4292-42d1-895e-249a5946aa74)

**Comment by magland** [comment]
@luiztauffer I believe this is because the docker images have not bee rebuilt since the changes. The system is in a transition state right now where the new changes have not yet been propagated or tested.

**Comment by luiztauffer** [comment]
I understand, just reporting anyway.
I forgot to mention I built the image locally, so docker run will probably pull the most updated image. Although it might not contain the most updated ProtoCAAS python package inside of it...
Any idea on why it gets stuck in `Running: docker run -it v ...`? It would be helpful to get an Exception instead

**Comment by magland** [comment]
There should be a (limited) log file hidden somewhere in the job working directory /compute/resource/dir/jobs/<job_id>/*.log

That might give a clue

If the communication between the job process and the protocaas api is not functioning then you won't get anything in the GUI (such as console output). I guess we'll need to figure out how to deal with this.

**Comment by luiztauffer** [comment]
the job folder was created, but it's empty

**Comment by magland** [comment]
I'm going to redeploy everything shortly and then we can see.
