### ISSUE TITLE
Current Forms limitations

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#50]
The Forms do not handle well some cases (see image below):
- nested kwargs in general
- `electrical_series_path` as a nested kwarg
- List type
- Optional types, e.g. the argument type is integer but, as an optional type, it could receive None

source models: https://github.com/catalystneuro/si-dendro-apps/blob/main/si_kilosort25/models.py 

![image](https://github.com/flatironinstitute/dendro/assets/24541631/d3151851-1026-4b98-9c78-fe81a27226e6)
@magland

**Comment by magland** [comment]
Solved the nesting issue in #52 

For List, I think it's not bad as is... comma-separate list is pretty straightforward for a user.

I'll work on Optional type.

**Comment by luiztauffer** [comment]
@magland I agree the comma separated values is good enough for now, but is there any easy way we could indicate that's the case in the array fields? If I didn't know this is a comma-separated array of values, I would think this is just regular float

![image](https://github.com/flatironinstitute/dendro/assets/24541631/32331a57-19ae-4210-acbe-90e99c6233a3)
