### ISSUE TITLE
By default do not require CR restart when modifying app configuration

### ISSUE THREAD

**Issue by magland** [scratchrealm/protocaas#55]
By default do not require CR restart when modifying app configuration. However, let's have an env var set on the CR daemon that would require restart for new apps - for security reasons.

As discussed on slack with @luiztauffer

**Comment by magland** [comment]
Hmmm, or maybe we do it the other way. By default it requires a restart, but we can set an env variable that would not require restart, for convenience, in the case where we are confident that we don't have a security risk.

**Comment by luiztauffer** [comment]
this level of control sounds ideal

**Comment by magland** [comment]
and/or we'll require a password for performing sensitive operations on the web API. I think the password should be something set in an env var on the compute resource. (as proposed by Luiz on slack)

**Comment by magland** [comment]
Done. For now, no password is required.
