### ISSUE TITLE
Export Jobs as JSON files

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#58]
It would be useful to be able to export Jobs as json files from the UI.
This should be informative, e.g. contain source files, CR relevant info, logs, etc... so we could use these files to:

- require them in Issues related to job run errors
- share and reproduce Job runs

**Comment by magland** [comment]
In fact, I think we should be able to export an entire project as a json file. This should be very straightforward.

**Comment by magland** [comment]
@luiztauffer There is now an export job as JSON button in the job view

![image](https://github.com/flatironinstitute/dendro/assets/3679296/2d626e31-72cf-430b-b644-bba016948cae)

And it creates a file such as the one attached.

[dendro-job-c1687346.json](https://github.com/flatironinstitute/dendro/files/13382270/dendro-job-c1687346.json)
