### ISSUE TITLE
Error creating spike sorting view

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#70]
Got this error when trying to create a spike sorting view from a file that was produced by KS25 Processor

![image](https://github.com/flatironinstitute/dendro/assets/24541631/da54c1db-6e62-42e3-9fc8-e9bc63ea8c2c)

@magland

**Comment by magland** [comment]
This should be fixed now.

**Comment by luiztauffer** [comment]
fixed, thanks!
