### ISSUE TITLE
Update status and log for AWS Batch jobs

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#73]
@magland 
It seems we're not updating the status for Batch jobs.
This job was successfully submitted, but failed internally (volume mount error inside the running container). From AWS Batch console and boto3 client I can get the failed status and error log, but this is not being passed forward to Dendro.

![image](https://github.com/flatironinstitute/dendro/assets/24541631/2b3bf079-7125-441c-88b0-04dd4e9498c2)

**Comment by magland** [comment]
Yes, I agree! This will be important to add.

Right now the process launched by the controller is completely detached from the controller, and I like it this way. That way we can stop and start the controller without worrying about it affecting the running processes. And it just makes things a lot cleaner over all. But the downside is that if the subprocess crashes or fails, then that information is not communicated back to the controller, and so there's no way to update the status or the console output.

There are a lot of processes involved here. So we'll need to come up with a strategy for capturing the status/console at all the various levels.

In the case of local processing we have

controller -datached-> singularity command -> parent job process (in container) -> child job process (in container)

In the case of slurm we have

controller -detached-> srun command -> singularity command -> parent job process (in container) -> child job process (in container)

In the case of AWS Batch we have

controller -detached-> [some command??] -> AWS batch spins up the container -> parent job process (in container) -> child job process (in container)

**Comment by luiztauffer** [comment]
maybe related, when I restarted the compute resource, it crashed with this error track:
```
Loading app https://github.com/scratchrealm/pc-spike-sorting/blob/main/kilosort2_5/spec.json
  awsBatchJobQueue: DendroBatchStack-job-queue | awsBatchJobDefinition: kilosort25-dendro-jd
  3 processors


Reporting the compute resource spec
Getting pubsub info
Starting compute resource
Starting job f11943ec kilosort2_5
Error in processor put api request for https://dendro.vercel.app/api/processor/jobs/f11943ec/status; 500 Server Error: Internal Server Error for url: https://dendro.vercel.app/api/processor/jobs/f11943ec/status
Traceback (most recent call last):
  File "/home/ec2-user/dendro/python/dendro/compute_resource/JobManager.py", line 97, in _start_job
    return _start_job(
  File "/home/ec2-user/dendro/python/dendro/compute_resource/_start_job.py", line 47, in _start_job
    _set_job_status_to_starting(
  File "/home/ec2-user/dendro/python/dendro/compute_resource/_start_job.py", line 28, in _set_job_status_to_starting
    resp = _processor_put_api_request(
  File "/home/ec2-user/dendro/python/dendro/common/_api_request.py", line 148, in _processor_put_api_request
    resp.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://dendro.vercel.app/api/processor/jobs/f11943ec/status
Failed to start job: 500 Server Error: Internal Server Error for url: https://dendro.vercel.app/api/processor/jobs/f11943ec/status

```
