### ISSUE TITLE
should we use black for code formatting?

### ISSUE THREAD

**Issue by magland** [scratchrealm/protocaas#8]
@luiztauffer Should we use "black" for code formatting?

**Comment by luiztauffer** [comment]
Personally, I dislike it, and never felt advantage using it. Some of the enforced formatting becomes actually less legible, imo, and most of good practices for legibility are not difficult to be followed without it anyway. At the end of the day, it's a matter of taste I guess. Have you tried it?

**Comment by magland** [comment]
I haven't tried it. I would like to conform to recommended formatting though. I just installed pylint and it picks up a lot of issues. Some I want to ignore, but others are helpful - like not allowing exceptions that are too general. Trailing whitespace is something I'd like to get rid of on lines. And should we enforce newline at the end of a file? Maybe we could have a script that does that. IDK, what do you think?

**Comment by luiztauffer** [comment]
there are a couple of strict rules that actually makes the code look quite bad, and one simply can't control that after adopting black.
e.g., something nicely formatted like this:
```
def myfunc(
    arg1: type = default_value,
    arg2: type = default_value,
    arg3: type = default_value,
):
    ...
```

could be enforced by black into a monster like this, based only on the number of characters inside the myfunc definition:
```
def myfunc(
    arg1: type = default_value, arg2: type = default_value, arg3: type = default_value):
    ...
```

**Comment by luiztauffer** [comment]
a good linter should be enough imo
